[package]
name = "HabitPlatform"
version = "1.0.0"
authors = ["Habit Team"]

[addresses]
habit = "0x78be456e78ffec3148be7b55580d91adc963e6affdf5a77672d31e44c0baa84c"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
